"""The notification settings page and both agent modals actually render.

The badges and checkboxes are generated by iterating the event catalogue, and a
Jinja typo or a context variable that fails to reach the operational-events
partial 500s the settings page without any other test noticing.
"""

import pytest

from app.extensions import db
from app.models import AdminAccount, Notification, Settings
from app.services.notification_events import (
    OPERATIONAL_EVENT_TYPES,
    SUBSCRIBABLE_EVENT_TYPES,
)


@pytest.fixture
def logged_in(app, session, client):
    with app.app_context():
        admin = AdminAccount.query.filter_by(username="uiadmin").first()
        if not admin:
            admin = AdminAccount(username="uiadmin")
            admin.set_password("uipass")
            db.session.add(admin)
        if not Settings.query.filter_by(key="admin_username").first():
            db.session.add(Settings(key="admin_username", value="uiadmin"))
        db.session.commit()

    with client.session_transaction() as sess:
        sess["_user_id"] = "1"
        sess["_fresh"] = True
    return client


@pytest.fixture
def agent(app, session):
    with app.app_context():
        Notification.query.delete()
        row = Notification(
            name="UI agent",
            type="ntfy",
            url="https://ntfy.example/ui",
            notification_events="user_joined",
        )
        db.session.add(row)
        db.session.commit()
        return row.id


def test_settings_page_renders_event_badges(logged_in, agent):
    response = logged_in.get("/settings/notifications/", follow_redirects=True)

    assert response.status_code == 200
    body = response.get_data(as_text=True)
    # Subscribed one is shown, unsubscribed one is not.
    assert "User Joined" in body
    assert "Update Available" not in body
    # Operational events show regardless of what the row stores.
    for event in OPERATIONAL_EVENT_TYPES:
        assert event.label in body


def test_create_modal_renders_every_checkbox(logged_in):
    response = logged_in.get("/settings/notifications/create", follow_redirects=True)

    assert response.status_code == 200
    body = response.get_data(as_text=True)
    for event in SUBSCRIBABLE_EVENT_TYPES:
        assert f'name="event_{event.key}"' in body
    # Operational ones appear as disabled, never as a submittable field.
    for event in OPERATIONAL_EVENT_TYPES:
        assert f'name="event_{event.key}"' not in body
        assert f'id="operational_{event.key}"' in body


def test_edit_modal_reflects_stored_subscription(logged_in, agent):
    response = logged_in.get(
        f"/settings/notifications/edit/{agent}", follow_redirects=True
    )

    assert response.status_code == 200
    body = response.get_data(as_text=True)
    for event in SUBSCRIBABLE_EVENT_TYPES:
        assert f'name="event_{event.key}"' in body
